version: '3.2'

services:
  entitlements:
    build:
      context: ./
      dockerfile: ./Dockerfile
    links:
      - redis
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - DEMO_MODE=true
    restart: unless-stopped

  redis:
    image: registry.access.redhat.com/rhscl/redis-32-rhel7:latest
    ports:
      - 6379:6379
    restart: always
